sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install coveralls tox-travis

script:
  - tox -- --cov-append

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=flake8
      script: tox -e $TOX_ENV
    - python: 3.7
      dist: xenial
      sudo: true

after_success:
  - coveralls
